# GET https://localhost:3000/

POST https://localhost:3000/api/links
Content-Type: application/json

{
    "code": "test",
    "url": "https://yagasaki.dev/"
}

### 

GET https://localhost:3000/api/links

###

GET https://localhost:3000/yagasaki.dev

###

GET https://localhost:3000/api/metrics